**// 25AIML060 //
NIYATI RAIYANI //
AIUC202_DATA ANALYSIS WITH PYTHON //
CSPIT-AIML // 
BATCH-C // **

Step 1 – Import Pandas

In [6]:
import numpy as np
import pandas as pd

Step 2-Load the dataset

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\hppc\Downloads\amazon - amazon.csv")

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
df.head(10)

Number of rows: 1465
Number of columns: 16

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
5,B08Y1TFSP6,pTron Solero TB301 3A Type-C Data and Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹149,"₹1,000",85%,3.9,"24,871",Fast Charging & Data Sync: Solero TB301 Type-C...,"AEQ2YMXSZWEOHK2EHTNLOS56YTZQ,AGRVINWECNY7323CW...","Jayesh,Rajesh k.,Soopy,amazon customer,Aman,Sh...","R7S8ANNSDPR40,R3CLZFLHVJU26P,RFF7U7MPQFUGR,R1M...","It's pretty good,Average quality,very good and...","It's a good product.,Like,Very good item stron...",https://m.media-amazon.com/images/I/31wOPjcSxl...,https://www.amazon.in/Solero-TB301-Charging-48...
6,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro US...",Computers&Accessories|Accessories&Peripherals|...,₹176.63,₹499,65%,4.1,"15,188",It Ensures High Speed Transmission And Chargin...,"AG7C6DAADCTRQJG2BRS3RIKDT52Q,AFU7BOMPVJ7Q3TTA4...","Vivek kumar,Amazon Customer,SARTHAK,Chiranjeev...","R8E73K2KWJRDS,RSD0JTIIWQQL8,R64CRSTE9SLW1,R2FR...","Long durable.,good,Does not charge Lenovo m8 t...",Build quality is good and it is comes with 2 y...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/boAt-Micro-USB-Tangle-Fr...
7,B08DDRGWTJ,MI Usb Type-C Cable Smartphone (Black),Computers&Accessories|Accessories&Peripherals|...,₹229,₹299,23%,4.3,"30,411",1m long Type-C USB Cable|Sturdy and Durable. W...,"AHW6E5LQ2BDYOIVLAJGDH45J5V5Q,AF74RSGCHPZITVFSZ...","Pavan A H,Jayesh bagad,Shridhar,rajendran,karu...","R2X090D1YHACKR,R32ZCIH9AFNJ60,R3N57EVVG0EHAF,R...","Worth for money - suitable for Android auto,Go...",Worth for money - suitable for Android auto......,https://m.media-amazon.com/images/I/31XO-wfGGG...,https://www.amazon.in/MI-MTCY001IN-USB-Type-C-...
8,B008IFXQFU,"TP-Link USB WiFi Adapter for PC(TL-WN725N), N1...",Computers&Accessories|NetworkingDevices|Networ...,₹499,₹999,50%,4.2,"1,79,691",USB WiFi Adapter —— Speedy wireless transmissi...,"AGV3IEFANZCKECFGUM42MRH5FNOA,AEBO7NWCNXKT4AESA...","Azhar JuMan,Anirudh Sood,Hari Krishnan PS,Akas...","R1LW6NWSVTVZ2H,R3VR5WFKUS15C5,R2F6GC79OYWUKQ,R...",Works on linux for me. Get the model with ante...,I use this to connect an old PC to internet. I...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/TP-Link-TL-WN725N-150Mbp...
9,B082LZGK39,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹299,33%,4,"43,994",Universal Compatibility – It is compatible wit...,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...

Step-3 Understand the dataset

In [2]:
print("Column names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nDataset information:")
df.info()

Column names:
['product_id', 'product_name', 'category', 'discounted_price', 'actual_price', 'discount_percentage', 'rating', 'rating_count', 'about_product', 'user_id', 'user_name', 'review_id', 'review_title', 'review_content', 'img_link', 'product_link']

Data types:
product_id             str
product_name           str
category               str
discounted_price       str
actual_price           str
discount_percentage    str
rating                 str
rating_count           str
about_product          str
user_id                str
user_name              str
review_id              str
review_title           str
review_content         str
img_link               str
product_link           str
dtype: object

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   str
 4   actual_price         1465 non-null   str
 5   discount_percentage  1465 non-null   str
 6   rating               1465 non-null   str
 7   rating_count         1463 non-null   str
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
dtypes: str(16)
memory usage: 183.3 KB

Step-4 Check missing values

In [3]:
missing_values = df.isnull().sum()
missing_values.sort_values(ascending=False)

rating_count           2
product_id             0
category               0
product_name           0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

Step-5 Clean numerical columns

In [7]:
# Clean numerical columns

df['discounted_price'] = (
    df['discounted_price']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

df['actual_price'] = (
    df['actual_price']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

df['discount_percentage'] = (
    df['discount_percentage']
    .astype(str)
    .str.replace('%', '', regex=False)
    .astype(float)
)

df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

df["rating_count"] = (
    df["rating_count"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .replace("nan", np.nan)
)
df["rating_count"] = pd.to_numeric(df["rating_count"], errors="coerce")

df[["discounted_price", "actual_price", "discount_percentage",
    "rating", "rating_count"]].head()

   discounted_price  actual_price  discount_percentage  rating  rating_count
0             399.0        1099.0                 64.0     4.2       24269.0
1             199.0         349.0                 43.0     4.0       43994.0
2             199.0        1899.0                 90.0     3.9        7928.0
3             329.0         699.0                 53.0     4.2       94363.0
4             154.0         399.0                 61.0     4.2       16905.0

Step-6 create a discount amount column

In [8]:
df["discount_amount"] = (
    df["actual_price"] - df["discounted_price"]
)

df[["product_name", "actual_price", "discounted_price", "discount_amount"]].head()

,product_name,actual_price,discounted_price,discount_amount
0,Wayona Nylon Braided USB to Lightning Fast Cha...,1099.0,399.0,700.0
1,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,349.0,199.0,150.0
2,Sounce Fast Phone Charging Cable & Data Sync U...,1899.0,199.0,1700.0
3,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,699.0,329.0,370.0
4,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,399.0,154.0,245.0

Step 7 - use Numpy for statiscal calculations

In [9]:
ratings = df["rating"].dropna().to_numpy()

print(ratings)
print("Average rating:", np.mean(ratings))
print("Minimum rating:", np.min(ratings))
print("Maximum rating:", np.max(ratings))
print("Standard deviation:", np.std(ratings))

[4.2 4.  3.9 ... 3.6 4.  4.3]
Average rating: 4.096584699453552
Minimum rating: 2.0
Maximum rating: 5.0
Standard deviation: 0.2915744469711793

Step-8 Find highly rated products using Numpy

In [10]:
df["rating_status"] = np.where(
    df["rating"] >= 4.0,
    "Highly Rated",
    "Below 4.0"
)

df[["product_name", "rating", "rating_status"]].head(10)

                                        product_name  rating rating_status
0  Wayona Nylon Braided USB to Lightning Fast Cha...     4.2  Highly Rated
1  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...     4.0  Highly Rated
2  Sounce Fast Phone Charging Cable & Data Sync U...     3.9     Below 4.0
3  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...     4.2  Highly Rated
4  Portronics Konnect L 1.2M Fast Charging 3A 8 P...     4.2  Highly Rated
5  pTron Solero TB301 3A Type-C Data and Fast Cha...     3.9     Below 4.0
6  boAt Micro USB 55 Tangle-free, Sturdy Micro US...     4.1  Highly Rated
7             MI Usb Type-C Cable Smartphone (Black)     4.3  Highly Rated
8  TP-Link USB WiFi Adapter for PC(TL-WN725N), N1...     4.2  Highly Rated
9  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...     4.0  Highly Rated

Step - 9 - Find products with high discounts

In [11]:
high_discount = df[df["discount_percentage"] >= 50]

print("Number of products with 50% or more discount:",
      len(high_discount))

high_discount.head(10)

Number of products with 50% or more discount: 751

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,discount_amount,rating_status
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.00,1099.0,64.0,4.2,24269.0,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...,700.00,Highly Rated
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.00,1899.0,90.0,3.9,7928.0,【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...,1700.00,Below 4.0
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.00,699.0,53.0,4.2,94363.0,The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...,370.00,Highly Rated
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.00,399.0,61.0,4.2,16905.0,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...,245.00,Highly Rated
5,B08Y1TFSP6,pTron Solero TB301 3A Type-C Data and Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,149.00,1000.0,85.0,3.9,24871.0,Fast Charging & Data Sync: Solero TB301 Type-C...,"AEQ2YMXSZWEOHK2EHTNLOS56YTZQ,AGRVINWECNY7323CW...","Jayesh,Rajesh k.,Soopy,amazon customer,Aman,Sh...","R7S8ANNSDPR40,R3CLZFLHVJU26P,RFF7U7MPQFUGR,R1M...","It's pretty good,Average quality,very good and...","It's a good product.,Like,Very good item stron...",https://m.media-amazon.com/images/I/31wOPjcSxl...,https://www.amazon.in/Solero-TB301-Charging-48...,851.00,Below 4.0
6,B08WRWPM22,"boAt Micro USB 55 Tangle-free, Sturdy Micro US...",Computers&Accessories|Accessories&Peripherals|...,176.63,499.0,65.0,4.1,15188.0,It Ensures High Speed Transmission And Chargin...,"AG7C6DAADCTRQJG2BRS3RIKDT52Q,AFU7BOMPVJ7Q3TTA4...","Vivek kumar,Amazon Customer,SARTHAK,Chiranjeev...","R8E73K2KWJRDS,RSD0JTIIWQQL8,R64CRSTE9SLW1,R2FR...","Long durable.,good,Does not charge Lenovo m8 t...",Build quality is good and it is comes with 2 y...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/boAt-Micro-USB-Tangle-Fr...,322.37,Highly Rated
8,B008IFXQFU,"TP-Link USB WiFi Adapter for PC(TL-WN725N), N1...",Computers&Accessories|NetworkingDevices|Networ...,499.00,999.0,50.0,4.2,179691.0,USB WiFi Adapter —— Speedy wireless transmissi...,"AGV3IEFANZCKECFGUM42MRH5FNOA,AEBO7NWCNXKT4AESA...","Azhar JuMan,Anirudh Sood,Hari Krishnan PS,Akas...","R1LW6NWSVTVZ2H,R3VR5WFKUS15C5,R2F6GC79OYWUKQ,R...",Works on linux for me. Get the model with ante...,I use this to connect an old PC to internet. I...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/TP-Link-TL-WN725N-150Mbp...,500.00,Highly Rated
10,B08CF3D7QR,Portronics Konnect L POR-1081 Fast Charging 3A...,Computers&Accessories|Accessories&Peripherals|...,154.00,339.0,55.0,4.3,13391.0,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AGYLPKPZHVYKKZHOTHCTYVEDAJ4A,AGTTU64JMX722LYCN...","Tanya,Anu,Akshay,Vishal Sagara Shetty,Swatilek...","R11MQS7WD9C3I0,R2AKH69XQY8BY4,R8GBOLYUN5UP6,R1...",Good for fast charge but not for data transfer...,The cable is efficient in fast charging but in...,https://m.media-amazon.com/images/I/31dJ+lXJq3...,https://www.amazon.in/Portronics-POR-1081-Char...,185.00,Highly Rated
11,B0789LZTCJ,boAt Rugged v3 Extra Tough Unbreakable Braided...,Computers&Accessories|Accessories&Peripherals|...,299.00,799.0,63.0,4.2,94363.0,The boAt rugged cable features our special tou...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41SDfuK7L2...,https://www.amazon.in/Rugged-Extra-Tough-Unbre...,500.00,Highly Rated
12,B07KSMBL2H,AmazonBasics Flexible Premium HDMI Cable (Blac...,"Electronics|HomeTheater,TV&Video|Accessories|C...",219.00,700.0,69.0,4.4,426973.0,"Flexible, lightweight HDMI cable for connectin...","AEYJ5I6JZZPOJB6MGWRQOHRQLPSQ,AFY5TVFOMVHGBPBTI...","Rishav Gossain,Shashank Mallamraju,Purnendu,gu...","R1FKOKZ3HHKJBZ,R2WNMZI1EXTA0H,RCA1M3W4RIXUR,R3...","It's quite good and value for money,Works well...",I am using it for 14 days now. The experience ...,https://m.media-amazon.com/images/I/41nPYaWA+M...,https://www.amazon.in/AmazonBasics-Flexible-HD...,481.00,Highly Rated

Step-10 Find the top 10most highly rated products

In [12]:
top_rated = (
    df[df["rating_count"] >= 100]
    .sort_values(["rating", "rating_count"], ascending=[False, False])
)

top_rated[
    ["product_name", "rating", "rating_count", "discounted_price"]
].head(10)

,product_name,rating,rating_count,discounted_price
1145,Swiffer Instant Electric Water Heater Faucet T...,4.8,53803.0,1439.0
1299,"Instant Pot Air Fryer, Vortex 2QT, Touch Contr...",4.8,3964.0,4995.0
459,Spigen EZ Fit Tempered Glass Screen Protector ...,4.7,7779.0,999.0
249,Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...,4.7,5935.0,77990.0
1388,Campfire Spring Chef Prolix Instant Portable W...,4.7,2591.0,1499.0
1275,Multifunctional 2 in 1 Electric Egg Boiling St...,4.7,2300.0,699.0
1223,"FIGMENT Handheld Milk Frother Rechargeable, 3-...",4.7,1729.0,699.0
820,Redgear MP35 Speed-Type Gaming Mousepad (Black...,4.6,33434.0,299.0
447,Spigen EZ Fit Tempered Glass Screen Protector ...,4.6,26603.0,999.0
886,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",4.6,12375.0,1295.0

Step-11 Category Analysis

In [13]:
list(df['category'].head(10))

['Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables',
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables',
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables',
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables',
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables',
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables',
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables',
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables',
 'Computers&Accessories|NetworkingDevices|NetworkAdapters|WirelessUSBAdapters',
 'Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables']

In [14]:
df["main_category"] = df["category"].astype(str).str.split("|").str[0]

df["main_category"].value_counts().head(10)

main_category
Electronics              526
Computers&Accessories    453
Home&Kitchen             448
OfficeProducts            31
MusicalInstruments         2
HomeImprovement            2
Toys&Games                 1
Car&Motorbike              1
Health&PersonalCare        1
Name: count, dtype: int64

Step-12 Calculate category wise statics

In [15]:
category_summary = (
    df.groupby("main_category")
      .agg(
          product_count=("product_id", "count"),
          average_rating=("rating", "mean"),
          average_discount=("discount_percentage", "mean"),
          average_price=("discounted_price", "mean")
      )
      .sort_values("product_count", ascending=False)
)

category_summary.head(10)

,product_count,average_rating,average_discount,average_price
main_category,,,,
Electronics,526,4.081749,50.828897,5965.887833
Computers&Accessories,453,4.154967,54.024283,842.650375
Home&Kitchen,448,4.040716,40.120536,2330.615647
OfficeProducts,31,4.309677,12.354839,301.580645
MusicalInstruments,2,3.900000,46.000000,638.000000
HomeImprovement,2,4.250000,57.500000,337.000000
Car&Motorbike,1,3.800000,42.000000,2339.000000
Health&PersonalCare,1,4.000000,53.000000,899.000000
Toys&Games,1,4.300000,0.000000,150.000000

Step-13 find the most reviewed products

In [16]:
most_reviewed = df.sort_values(
    "rating_count", ascending=False
)

most_reviewed[
    ["product_name", "rating", "rating_count", "discounted_price"]
].head(10)

,product_name,rating,rating_count,discounted_price
47,"Amazon Basics High-Speed HDMI Cable, 6 Feet - ...",4.4,426973.0,309.0
65,"Amazon Basics High-Speed HDMI Cable, 6 Feet (2...",4.4,426973.0,309.0
12,AmazonBasics Flexible Premium HDMI Cable (Blac...,4.4,426973.0,219.0
684,AmazonBasics Flexible Premium HDMI Cable (Blac...,4.4,426972.0,219.0
400,boAt Bassheads 100 in Ear Wired Earphones with...,4.1,363713.0,379.0
352,boAt Bassheads 100 in Ear Wired Earphones with...,4.1,363713.0,349.0
584,boAt BassHeads 100 in-Ear Wired Headphones wit...,4.1,363711.0,365.0
371,"Redmi 9A Sport (Coral Green, 2GB RAM, 32GB Sto...",4.1,313836.0,6499.0
370,"Redmi 9 Activ (Carbon Black, 4GB RAM, 64GB Sto...",4.1,313836.0,8499.0
566,"Redmi 9A Sport (Coral Green, 3GB RAM, 32GB Sto...",4.1,313832.0,7499.0

Step 14 — NumPy: calculate the overall price statistics

In [17]:
prices = df["discounted_price"].dropna().to_numpy()

print("Average discounted price:", np.mean(prices))
print("Median discounted price:", np.median(prices))
print("Minimum discounted price:", np.min(prices))
print("Maximum discounted price:", np.max(prices))

Average discounted price: 3125.3108737201364
Median discounted price: 799.0
Minimum discounted price: 39.0
Maximum discounted price: 77990.0

Step-15 create a simple final summery

In [18]:
summary = pd.DataFrame({
    "Metric": [
        "Total Products",
        "Average Rating",
        "Average Discount %",
        "Average Discounted Price",
        "Products with >= 50% Discount"
    ],
    "Value": [
        len(df),
        round(df["rating"].mean(), 2),
        round(df["discount_percentage"].mean(), 2),
        round(df["discounted_price"].mean(), 2),
        int((df["discount_percentage"] >= 50).sum())
    ]
})

summary

                          Metric    Value
0                 Total Products  1465.00
1                 Average Rating     4.10
2             Average Discount %    47.69
3       Average Discounted Price  3125.31
4  Products with >= 50% Discount   751.00